export const data = [
  {
    id: 1,
    name: "Harry Potter",
    img: "https://upload.wikimedia.org/wikipedia/en/d/d7/Harry_Potter_character_poster.jpg",
    statistics: [
      "Leader of Dumbledore's Army",
      "Defeated Voldemort",
      "Skilled in Defense Against the Dark Arts",
    ],
    profile: "https://harrypotter.fandom.com/wiki/Harry_Potter",
    official_career: "Gryffindor",
  },
  {
    id: 2,
    name: "Hermione Granger",
    img: "https://upload.wikimedia.org/wikipedia/en/d/d3/Hermione_Granger_poster.jpg",
    statistics: [
      "Brilliant Strategist",
      "Expert in Spell Casting",
      "Top Student at Hogwarts",
    ],
    profile: "https://harrypotter.fandom.com/wiki/Hermione_Granger",
    official_career: "Gryffindor",
  },
  {
    id: 3,
    name: "Ron Weasley",
    img: "https://upload.wikimedia.org/wikipedia/en/5/5e/Ron_Weasley_poster.jpg",
    statistics: [
      "Courageous Companion",
      "Excellent Chess Player",
      "Defeated Horcruxes",
    ],
    profile: "https://harrypotter.fandom.com/wiki/Ron_Weasley",
    official_career: "Gryffindor",
  },
  {
    id: 4,
    name: "Neville Longbottom",
    img: "https://avatars.dzeninfra.ru/get-zen_doc/4491962/pub_6090ef5ca5f87026b1126195_6090f0364fade3788b6152c6/scale_1200",
    statistics: ["Destroyed Nagini", "Herbology Expert", "Defied Voldemort"],
    profile: "https://harrypotter.fandom.com/wiki/Neville_Longbottom",
    official_career: "Gryffindor",
  },
  {
    id: 5,
    name: "Luna Lovegood",
    img: "https://media.harrypotterfanzone.com/luna-lovegood-half-blood-prince-portrait-2-1050x0-c-default.jpg",
    statistics: ["Exceptional Insight", "Loyal Friend", "Inventive Thinker"],
    profile: "https://harrypotter.fandom.com/wiki/Luna_Lovegood",
    official_career: "Ravenclaw",
  },
  {
    id: 6,
    name: "Ginny Weasley",
    img: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/fe007304-e5bf-4f3d-9ce9-b6b25d728069/1920x",
    statistics: [
      "Talented Duelist",
      "Chaser for Gryffindor Quidditch Team",
      "Fought in the Battle of Hogwarts",
    ],
    profile: "https://harrypotter.fandom.com/wiki/Ginny_Weasley",
    official_career: "Gryffindor",
  },
  {
    id: 7,
    name: "Cho Chang",
    img: "https://static1.srcdn.com/wordpress/wp-content/uploads/2019/04/Cho-Chang-Harry-Potter.jpg?q=50&fit=crop&w=1140&h=&dpr=1.5",
    statistics: [
      "Seeker for Ravenclaw Quidditch Team",
      "Member of Dumbledore's Army",
      "Skilled Flier",
    ],
    profile: "https://harrypotter.fandom.com/wiki/Cho_Chang",
    official_career: "Ravenclaw",
  },
  {
    id: 8,
    name: "Fred Weasley",
    img: "https://wizardswelcome.com/wp-content/uploads/2022/05/Screenshot-at-May-04-05-11-45.png",
    statistics: [
      "Co-Founder of Weasleys' Wizard Wheezes",
      "Prankster Extraordinaire",
      "Brave Fighter in the Battle of Hogwarts",
    ],
    profile: "https://harrypotter.fandom.com/wiki/Fred_Weasley",
    official_career: "Gryffindor",
  },
  {
    id: 9,
    name: "George Weasley",
    img: "https://media.harrypotterfanzone.com/george-weasley-order-of-the-phoenix-portrait-2-1050x0-c-default.jpg",
    statistics: [
      "Co-Founder of Weasleys' Wizard Wheezes",
      "Inventive Prankster",
      "Loyal Fighter in the Order of the Phoenix",
    ],
    profile: "https://harrypotter.fandom.com/wiki/George_Weasley",
    official_career: "Gryffindor",
  },
  {
    id: 10,
    name: "Seamus Finnigan",
    img: "https://i.pinimg.com/736x/b9/eb/75/b9eb755395e9ccf8bcd8d5b809f1b6a3.jpg",
    statistics: [
      "Expert in Explosive Spells",
      "Loyal Member of Dumbledore's Army",
      "Fought in the Battle of Hogwarts",
    ],
    profile: "https://harrypotter.fandom.com/wiki/Seamus_Finnigan",
    official_career: "Gryffindor",
  },
];
